# Generated by Django 3.2.8 on 2021-10-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPIArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
            ],
            options={
                'verbose_name': 'область КПЭ',
                'verbose_name_plural': 'области КПЭ',
            },
        ),
        migrations.CreateModel(
            name='KPIIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('description', models.TextField(max_length=2048, verbose_name='описание')),
                ('target_value', models.PositiveSmallIntegerField(verbose_name='целевое значние')),
            ],
            options={
                'verbose_name': 'показатель КПЭ',
                'verbose_name_plural': 'показатели КПЭ',
            },
        ),
        migrations.CreateModel(
            name='KPIEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.PositiveSmallIntegerField(verbose_name='значние')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_stats.kpiindex', verbose_name='показатель КПЭ')),
            ],
            options={
                'verbose_name': 'значение показателя КПЭ',
                'verbose_name_plural': 'значения показателя КПЭ',
            },
        ),
    ]
