name: deploy front
on:
  workflow_dispatch:

jobs:
  deploy-front:
    runs-on: ubuntu-latest
    steps:
      - name: deploy production with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/accenture-case-2021/accenture
            git pull
            cd ..
            docker-compose -f production.yml down
            docker-compose -f production.yml up --detach --build --force-recreate